/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2026-01-10 01:54:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.usm.bookhub.util.FileManager;
import java.io.File;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.usm.bookhub.util.FileManager");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 1. Security Check
    String userID = (String) session.getAttribute("userID");
    String userName = (String) session.getAttribute("userName");

    if (userName == null || userID == null) {
        response.sendRedirect("index.jsp");
        return;
    }

    // 2. Fetch Full User Details
    // 🟢 FIXED: We pass 'application' (which is the JSP word for ServletContext)
    String[] userDetails = FileManager.getUserByID(application, userID);

    // Default values
    String email = "N/A";
    String phone = "N/A";
    String address = "N/A";
    String major = "N/A";

    // 3. Extract data if found
    if (userDetails != null && userDetails.length >= 7) {
        email = userDetails[1];
        phone = userDetails[4];
        address = userDetails[5];
        major = userDetails[6];
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>BookHub Dashboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* --- 1. CSS VARIABLES --- */\r\n");
      out.write("        :root {\r\n");
      out.write("            --main-purple: #DDA0DD;\r\n");
      out.write("            --darker-purple: #BA55D3;\r\n");
      out.write("            --text-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- 2. HEADER --- */\r\n");
      out.write("        .header {\r\n");
      out.write("            background-color: var(--main-purple);\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            margin: 10px 0 0 0;\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            background-color: rgba(255,255,255,0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover { background-color: rgba(255,255,255,0.4); }\r\n");
      out.write("\r\n");
      out.write("        .logo-placeholder { font-size: 50px; }\r\n");
      out.write("\r\n");
      out.write("        /* --- 3. PROFILE SECTION --- */\r\n");
      out.write("        .profile-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: flex-end;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-info {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-info h1 {\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            line-height: 1.4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            min-width: 90px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-value { flex: 1; }\r\n");
      out.write("\r\n");
      out.write("        .profile-buttons {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            align-items: flex-end;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- QR CODE BOX --- */\r\n");
      out.write("        .qr-section {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-self: center;\r\n");
      out.write("            padding: 0 20px\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qr-box {\r\n");
      out.write("            width: 160px;\r\n");
      out.write("            height: 160px;\r\n");
      out.write("            background-color: #f4f4f4;\r\n");
      out.write("            border: 3px dashed #ccc;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #888;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-shadow: inset 0 0 10px rgba(0,0,0,0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-btn {\r\n");
      out.write("            background-color: var(--darker-purple);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-btn:hover { background-color: #9932CC; transform: scale(1.02); }\r\n");
      out.write("\r\n");
      out.write("        /* --- 4. TABS & STICKY WRAPPER --- */\r\n");
      out.write("        .sticky-wrapper {\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            box-shadow: 0px 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab-bar {\r\n");
      out.write("            background-color: var(--main-purple);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab-button {\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab-button.active {\r\n");
      out.write("            background-color: var(--darker-purple);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab-button:hover { background-color: rgba(255, 255, 255, 0.2); }\r\n");
      out.write("\r\n");
      out.write("        .search-container {\r\n");
      out.write("            background-color: var(--darker-purple);\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-input {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- 5. CONTENT AREA --- */\r\n");
      out.write("        .content-area {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            min-height: 800px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .inner-content {\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("            animation: fadeEffect 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeEffect { from {opacity: 0;} to {opacity: 1;} }\r\n");
      out.write("\r\n");
      out.write("        /* --- MODAL STYLES --- */\r\n");
      out.write("        .modal {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            z-index: 2000;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            margin: 10% auto;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.3);\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close-btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            right: 15px;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("        }\r\n");
      out.write("        .close-btn:hover { color: black; }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"file\"] {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px dashed #ccc;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function openTab(evt, tabName) {\r\n");
      out.write("            var i, tabcontent, tablinks;\r\n");
      out.write("            tabcontent = document.getElementsByClassName(\"tab-content\");\r\n");
      out.write("            for (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("                tabcontent[i].style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            tablinks = document.getElementsByClassName(\"tab-button\");\r\n");
      out.write("            for (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("                tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\r\n");
      out.write("            }\r\n");
      out.write("            document.getElementById(tabName).style.display = \"block\";\r\n");
      out.write("            evt.currentTarget.className += \" active\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function openQRModal() { document.getElementById(\"qrModal\").style.display = \"block\"; }\r\n");
      out.write("        function closeQRModal() { document.getElementById(\"qrModal\").style.display = \"none\"; }\r\n");
      out.write("\r\n");
      out.write("        function openEditModal() { document.getElementById(\"editModal\").style.display = \"block\"; }\r\n");
      out.write("        function closeEditModal() { document.getElementById(\"editModal\").style.display = \"none\"; }\r\n");
      out.write("\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            var m1 = document.getElementById(\"qrModal\");\r\n");
      out.write("            var m2 = document.getElementById(\"editModal\");\r\n");
      out.write("            if (event.target == m1) m1.style.display = \"none\";\r\n");
      out.write("            if (event.target == m2) m2.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function openAddBookModal() { document.getElementById(\"addBookModal\").style.display = \"block\"; }\r\n");
      out.write("        function closeAddBookModal() { document.getElementById(\"addBookModal\").style.display = \"none\"; }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\" class=\"logout-btn\">Logout ➜</a>\r\n");
      out.write("        <div class=\"logo-placeholder\">📚</div>\r\n");
      out.write("        <h1>USM Reference Book Hub</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"profile-container\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <h1>Welcome, ");
      out.print( userName );
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"info-row\">\r\n");
      out.write("                <span class=\"info-label\">Email:</span>\r\n");
      out.write("                <span class=\"info-value\">");
      out.print( email );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-row\">\r\n");
      out.write("                <span class=\"info-label\">Phone:</span>\r\n");
      out.write("                <span class=\"info-value\">");
      out.print( phone );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-row\">\r\n");
      out.write("                <span class=\"info-label\">Major:</span>\r\n");
      out.write("                <span class=\"info-value\">");
      out.print( major );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-row\">\r\n");
      out.write("                <span class=\"info-label\">Address:</span>\r\n");
      out.write("                <span class=\"info-value\">");
      out.print( address );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"qr-section\">\r\n");
      out.write("            ");

                String qrPath = null;
                String[] exts = {".jpg", ".jpeg", ".png"};

                // 🟢 FIXED: NO MORE HARDCODED PATHS!
                // We ask 'application.getRealPath' to find the folder on ANY computer.
                for (String ext : exts) {
                    String relativePath = "/images/profiles/" + userID + ext;
                    String realPath = application.getRealPath(relativePath);

                    File checkFile = new File(realPath);
                    if (checkFile.exists()) {
                        qrPath = "images/profiles/" + userID + ext; // Found it!
                        break;
                    }
                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (qrPath != null) { 
      out.write("\r\n");
      out.write("                <img src=\"");
      out.print( qrPath );
      out.write('?');
      out.write('t');
      out.write('=');
      out.print( System.currentTimeMillis() );
      out.write("\"\r\n");
      out.write("                     style=\"width: 160px; height: 160px; border-radius: 25px; border: 3px solid #BA55D3; object-fit: cover;\">\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"qr-box\">\r\n");
      out.write("                    No QR Code 📷<br>\r\n");
      out.write("                    <span style=\"font-size:12px; font-weight:normal;\">(Please click \"Update QR\")</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"profile-buttons\">\r\n");
      out.write("            <button class=\"action-btn\" onclick=\"openAddBookModal()\">Add Book 📕</button>\r\n");
      out.write("            <button class=\"action-btn\" onclick=\"openQRModal()\">Update QR 📱</button>\r\n");
      out.write("            <button class=\"action-btn\">Chat 💬</button>\r\n");
      out.write("            <button class=\"action-btn\" onclick=\"openEditModal()\">Edit Profile ✏️</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sticky-wrapper\">\r\n");
      out.write("        <div class=\"tab-bar\">\r\n");
      out.write("            <button class=\"tab-button active\" onclick=\"openTab(event, 'Marketplace')\">Marketplace 🛒</button>\r\n");
      out.write("            <button class=\"tab-button\" onclick=\"openTab(event, 'History')\">History 📜</button>\r\n");
      out.write("            <button class=\"tab-button\" onclick=\"openTab(event, 'Inventory')\">My Inventory 📦</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search-container\">\r\n");
      out.write("            <span>Search 🔍</span>\r\n");
      out.write("            <input type=\"text\" class=\"search-input\" placeholder=\"Type book name...\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content-area\">\r\n");
      out.write("        <div id=\"Marketplace\" class=\"tab-content\" style=\"display: block;\">\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("                <h2>🛒 The Marketplace</h2>\r\n");
      out.write("                <p>Here you will see a list of books for sale.</p>\r\n");
      out.write("                <div style=\"border: 2px dashed #ccc; padding: 40px; color: #aaa; height: 500px;\">\r\n");
      out.write("                    [ Book List Placeholder ]\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"History\" class=\"tab-content\">\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("                <h2>📜 Order History</h2>\r\n");
      out.write("                <p>Here are your past transactions.</p>\r\n");
      out.write("                <div style=\"border: 2px dashed #ccc; padding: 40px; color: #aaa; height: 300px;\">\r\n");
      out.write("                    [ Order List Placeholder ]\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"Inventory\" class=\"tab-content\">\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("                <h2>📦 My Inventory</h2>\r\n");
      out.write("                <p>Books you have uploaded to sell.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"qrModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close-btn\" onclick=\"closeQRModal()\">&times;</span>\r\n");
      out.write("            <h2>Update QR Code 📱</h2>\r\n");
      out.write("            <p>Upload a screenshot of your TNG or DuitNow QR.</p>\r\n");
      out.write("            <form action=\"updateQR\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <input type=\"file\" name=\"qrFile\" accept=\"image/*\" required>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button type=\"submit\" class=\"action-btn\">Upload Now ⬆️</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"editModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close-btn\" onclick=\"closeEditModal()\">&times;</span>\r\n");
      out.write("            <h2>Edit Profile ✏️</h2>\r\n");
      out.write("            <form action=\"editProfile\" method=\"post\">\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 10px;\">\r\n");
      out.write("                    <label>Full Name:</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"fullName\" value=\"");
      out.print( userName );
      out.write("\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 10px;\">\r\n");
      out.write("                    <label>Phone:</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"phone\" value=\"");
      out.print( phone );
      out.write("\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 10px;\">\r\n");
      out.write("                    <label>Major:</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"major\" value=\"");
      out.print( major );
      out.write("\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 20px;\">\r\n");
      out.write("                    <label>Address:</label><br>\r\n");
      out.write("                    <textarea name=\"address\" rows=\"3\" required style=\"width:100%; padding: 8px;\">");
      out.print( address );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"action-btn\">Save Changes 💾</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"addBookModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close-btn\" onclick=\"closeAddBookModal()\">&times;</span>\r\n");
      out.write("            <h2>Sell a Book 📕</h2>\r\n");
      out.write("            <p>Enter the details below.</p>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"addBook\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 10px;\">\r\n");
      out.write("                    <label>Book Title:</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"title\" placeholder=\"e.g. Intro to Java Programming\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"display: flex; gap: 10px; margin-bottom: 10px;\">\r\n");
      out.write("                    <div style=\"flex: 1; text-align: left;\">\r\n");
      out.write("                        <label>Sale Price (RM):</label><br>\r\n");
      out.write("                        <input type=\"number\" name=\"salePrice\" step=\"0.01\" placeholder=\"50.00\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"flex: 1; text-align: left;\">\r\n");
      out.write("                        <label>Rent Price (RM/week):</label><br>\r\n");
      out.write("                        <input type=\"number\" name=\"rentPrice\" step=\"0.01\" placeholder=\"5.00\" required style=\"width:100%; padding: 8px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"text-align: left; margin-bottom: 10px;\">\r\n");
      out.write("                    <label>Book Cover Image:</label><br>\r\n");
      out.write("                    <input type=\"file\" name=\"bookImage\" accept=\"image/*\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"action-btn\">List Book Now 🚀</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
