/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2026-01-10 01:53:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Welcome to BookHub</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* --- 1. CSS VARIABLES (Purple Theme) --- */\r\n");
      out.write("        :root {\r\n");
      out.write("            --main-purple: #DDA0DD; /* Light Purple */\r\n");
      out.write("            --darker-purple: #BA55D3; /* Darker Purple */\r\n");
      out.write("            --deep-purple: #800080;\r\n");
      out.write("            --text-color: #333;\r\n");
      out.write("            --bg-gray: #f4f4f4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: var(--bg-gray);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh; /* Full screen height */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- 2. THE MAIN CARD --- */\r\n");
      out.write("        .container {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0px 10px 25px rgba(0,0,0,0.1);\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-top: 5px solid var(--darker-purple);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 { color: var(--deep-purple); margin-bottom: 5px; }\r\n");
      out.write("        p { color: #666; margin-top: 0; }\r\n");
      out.write("\r\n");
      out.write("        /* --- 3. FORM INPUTS --- */\r\n");
      out.write("        .input-group {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-group label {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input, select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            box-sizing: border-box; /* Ensures padding doesn't break width */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus {\r\n");
      out.write("            border-color: var(--darker-purple);\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- 4. BUTTONS --- */\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: var(--darker-purple);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover { background-color: var(--deep-purple); }\r\n");
      out.write("\r\n");
      out.write("        .toggle-link {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .toggle-link span {\r\n");
      out.write("            color: var(--deep-purple);\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- 5. HIDE/SHOW LOGIC --- */\r\n");
      out.write("        .hidden { display: none; }\r\n");
      out.write("\r\n");
      out.write("        /* Logo styling */\r\n");
      out.write("        .logo { font-size: 40px; margin-bottom: 10px; display: block;}\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleForms() {\r\n");
      out.write("            var loginForm = document.getElementById(\"login-section\");\r\n");
      out.write("            var signupForm = document.getElementById(\"signup-section\");\r\n");
      out.write("\r\n");
      out.write("            if (loginForm.style.display === \"none\") {\r\n");
      out.write("                loginForm.style.display = \"block\";\r\n");
      out.write("                signupForm.style.display = \"none\";\r\n");
      out.write("            } else {\r\n");
      out.write("                loginForm.style.display = \"none\";\r\n");
      out.write("                signupForm.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <span class=\"logo\">📚</span>\r\n");
      out.write("        <h1>USM BookHub</h1>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"login-section\">\r\n");
      out.write("            <p>Welcome back! Please login.</p>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"login\" method=\"post\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Email</label>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" placeholder=\"ali@student.usm.my\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Password</label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" placeholder=\"••••••••\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-primary\">LOGIN</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"toggle-link\">\r\n");
      out.write("                Don't have an account? <span onclick=\"toggleForms()\">Sign Up</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"signup-section\" class=\"hidden\" style=\"display: none;\">\r\n");
      out.write("            <p>Create your student account.</p>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"register\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Full Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"fullName\" placeholder=\"Ali Bin Abu\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>USM Email</label>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" placeholder=\"ali@student.usm.my\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Password</label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Phone Number</label>\r\n");
      out.write("                    <input type=\"text\" name=\"phone\" placeholder=\"012-3456789\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Dorm / Address</label>\r\n");
      out.write("                    <input type=\"text\" name=\"address\" placeholder=\"Desasiswa Tekun\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label>Major</label>\r\n");
      out.write("                    <select name=\"major\">\r\n");
      out.write("                        <option value=\"Computer Science\">Computer Science</option>\r\n");
      out.write("                        <option value=\"Accounting\">Accounting</option>\r\n");
      out.write("                        <option value=\"Engineering\">Engineering</option>\r\n");
      out.write("                        <option value=\"Arts\">Arts</option>\r\n");
      out.write("                        <option value=\"Other\">Other</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-primary\">CREATE ACCOUNT</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"toggle-link\">\r\n");
      out.write("                Already have an account? <span onclick=\"toggleForms()\">Login</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
